[package]
name = "spektar"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    ".",
    "crates/spektar-audio",
    "crates/spektar-spectrum",
    "crates/spektar-ui",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spektar-ui = { path = "crates/spektar-ui" }
